/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeightRouteImport } from './routes/weight'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as OneRepMaxesRouteImport } from './routes/one-rep-maxes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateProgramRouteImport } from './routes/create-program'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsProgramIdHistoryRouteImport } from './routes/programs/$programId/history'
import { Route as ProgramsProgramIdWeeksWeekIdLogsRouteImport } from './routes/programs/$programId/weeks/$weekId/logs'

const WeightRoute = WeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const OneRepMaxesRoute = OneRepMaxesRouteImport.update({
  id: '/one-rep-maxes',
  path: '/one-rep-maxes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateProgramRoute = CreateProgramRouteImport.update({
  id: '/create-program',
  path: '/create-program',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdHistoryRoute =
  ProgramsProgramIdHistoryRouteImport.update({
    id: '/programs/$programId/history',
    path: '/programs/$programId/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsProgramIdWeeksWeekIdLogsRoute =
  ProgramsProgramIdWeeksWeekIdLogsRouteImport.update({
    id: '/programs/$programId/weeks/$weekId/logs',
    path: '/programs/$programId/weeks/$weekId/logs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/create-program': typeof CreateProgramRoute
  '/login': typeof LoginRoute
  '/one-rep-maxes': typeof OneRepMaxesRoute
  '/program': typeof ProgramRoute
  '/weight': typeof WeightRoute
  '/programs/$programId/history': typeof ProgramsProgramIdHistoryRoute
  '/programs/$programId/weeks/$weekId/logs': typeof ProgramsProgramIdWeeksWeekIdLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/create-program': typeof CreateProgramRoute
  '/login': typeof LoginRoute
  '/one-rep-maxes': typeof OneRepMaxesRoute
  '/program': typeof ProgramRoute
  '/weight': typeof WeightRoute
  '/programs/$programId/history': typeof ProgramsProgramIdHistoryRoute
  '/programs/$programId/weeks/$weekId/logs': typeof ProgramsProgramIdWeeksWeekIdLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/create-program': typeof CreateProgramRoute
  '/login': typeof LoginRoute
  '/one-rep-maxes': typeof OneRepMaxesRoute
  '/program': typeof ProgramRoute
  '/weight': typeof WeightRoute
  '/programs/$programId/history': typeof ProgramsProgramIdHistoryRoute
  '/programs/$programId/weeks/$weekId/logs': typeof ProgramsProgramIdWeeksWeekIdLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/create-program'
    | '/login'
    | '/one-rep-maxes'
    | '/program'
    | '/weight'
    | '/programs/$programId/history'
    | '/programs/$programId/weeks/$weekId/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/create-program'
    | '/login'
    | '/one-rep-maxes'
    | '/program'
    | '/weight'
    | '/programs/$programId/history'
    | '/programs/$programId/weeks/$weekId/logs'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/create-program'
    | '/login'
    | '/one-rep-maxes'
    | '/program'
    | '/weight'
    | '/programs/$programId/history'
    | '/programs/$programId/weeks/$weekId/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CreateProgramRoute: typeof CreateProgramRoute
  LoginRoute: typeof LoginRoute
  OneRepMaxesRoute: typeof OneRepMaxesRoute
  ProgramRoute: typeof ProgramRoute
  WeightRoute: typeof WeightRoute
  ProgramsProgramIdHistoryRoute: typeof ProgramsProgramIdHistoryRoute
  ProgramsProgramIdWeeksWeekIdLogsRoute: typeof ProgramsProgramIdWeeksWeekIdLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weight': {
      id: '/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof WeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one-rep-maxes': {
      id: '/one-rep-maxes'
      path: '/one-rep-maxes'
      fullPath: '/one-rep-maxes'
      preLoaderRoute: typeof OneRepMaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-program': {
      id: '/create-program'
      path: '/create-program'
      fullPath: '/create-program'
      preLoaderRoute: typeof CreateProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/history': {
      id: '/programs/$programId/history'
      path: '/programs/$programId/history'
      fullPath: '/programs/$programId/history'
      preLoaderRoute: typeof ProgramsProgramIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/weeks/$weekId/logs': {
      id: '/programs/$programId/weeks/$weekId/logs'
      path: '/programs/$programId/weeks/$weekId/logs'
      fullPath: '/programs/$programId/weeks/$weekId/logs'
      preLoaderRoute: typeof ProgramsProgramIdWeeksWeekIdLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CreateProgramRoute: CreateProgramRoute,
  LoginRoute: LoginRoute,
  OneRepMaxesRoute: OneRepMaxesRoute,
  ProgramRoute: ProgramRoute,
  WeightRoute: WeightRoute,
  ProgramsProgramIdHistoryRoute: ProgramsProgramIdHistoryRoute,
  ProgramsProgramIdWeeksWeekIdLogsRoute: ProgramsProgramIdWeeksWeekIdLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
