/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OneRepMaxUserIdRouteImport } from './routes/one-rep-max/$userId'
import { Route as HistoryUserIdWorkoutProgramIdRouteImport } from './routes/history/$userId.$workoutProgramId'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OneRepMaxUserIdRoute = OneRepMaxUserIdRouteImport.update({
  id: '/one-rep-max/$userId',
  path: '/one-rep-max/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryUserIdWorkoutProgramIdRoute =
  HistoryUserIdWorkoutProgramIdRouteImport.update({
    id: '/history/$userId/$workoutProgramId',
    path: '/history/$userId/$workoutProgramId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/one-rep-max/$userId': typeof OneRepMaxUserIdRoute
  '/history/$userId/$workoutProgramId': typeof HistoryUserIdWorkoutProgramIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/one-rep-max/$userId': typeof OneRepMaxUserIdRoute
  '/history/$userId/$workoutProgramId': typeof HistoryUserIdWorkoutProgramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/one-rep-max/$userId': typeof OneRepMaxUserIdRoute
  '/history/$userId/$workoutProgramId': typeof HistoryUserIdWorkoutProgramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/one-rep-max/$userId'
    | '/history/$userId/$workoutProgramId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/one-rep-max/$userId'
    | '/history/$userId/$workoutProgramId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/one-rep-max/$userId'
    | '/history/$userId/$workoutProgramId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  OneRepMaxUserIdRoute: typeof OneRepMaxUserIdRoute
  HistoryUserIdWorkoutProgramIdRoute: typeof HistoryUserIdWorkoutProgramIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one-rep-max/$userId': {
      id: '/one-rep-max/$userId'
      path: '/one-rep-max/$userId'
      fullPath: '/one-rep-max/$userId'
      preLoaderRoute: typeof OneRepMaxUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$userId/$workoutProgramId': {
      id: '/history/$userId/$workoutProgramId'
      path: '/history/$userId/$workoutProgramId'
      fullPath: '/history/$userId/$workoutProgramId'
      preLoaderRoute: typeof HistoryUserIdWorkoutProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  OneRepMaxUserIdRoute: OneRepMaxUserIdRoute,
  HistoryUserIdWorkoutProgramIdRoute: HistoryUserIdWorkoutProgramIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
